var express = require("express");
var app = express();
var http = require("http");
var server = http.createServer(app);
const bodyParser = require("body-parser");
app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());
server.listen(3001);
const cookieParser = require("cookie-parser");
const group = require("./routes/groups");
const users = require("./routes/users");
const user_messages = require("./routes/user_messages");
const deletemessage = require("./routes/deletemessage");
const addmessage = require("./routes/sendmessage");
const login = require("./routes/login");
const user = require("./routes/connecteduser");
const register = require("./routes/register");
const addgp = require("./routes/addgroup");
const groups = require("./routes/groups");
const joingroup = require("./routes/joingroup");
const addmessagetogroup = require("./routes/addmessagetogroup");
const groupsmsg = require("./routes/groupsmessages");
const updateuserprofile = require("./routes/updateuser");
const editpass = require("./routes/editpassword");
const addfriend = require("./routes/addfriend");
const acceptinvit = require("./routes/acceptinvitation");
const removefriend = require("./routes/deletefriend");
const acceptinvit2=require('./routes/acceptinvit2')
app.use("/list", group);
app.use("/users", users);
app.use("/messages", user_messages);
app.use("/deletemessage", deletemessage);
app.use("/addmessage", addmessage);
app.use("/login", login);
app.use("/user", user);
app.use("/register", register);
app.use("/addgroup", addgp);
app.use("/groups", groups);
app.use("/joingroup", joingroup);
app.use("/addmsgroup", addmessagetogroup);
app.use("/groupsmsg", groupsmsg);
app.use("/updateuser", updateuserprofile);
app.use("/updatepassword", editpass);
app.use("/sentinvit", addfriend);
app.use("/acceptinvit", acceptinvit);
app.use("/removefriend", removefriend);
app.use('/acceptinvit2',acceptinvit2)
app.use(cookieParser);
